version: 2.1

orbs:
  docker: circleci/docker@2.1.3

workflows:
  build:
    jobs:
      - build-and-push:
          context:
            - docker-hub-creds
          filters:
            branches:
              only: master

jobs:
  build-and-push:
    docker:
      - image: cimg/base:current
        auth:
          username: $DOCKER_LOGIN
          password: $DOCKER_PASSWORD
    steps:
      - add_ssh_keys:
          fingerprints:
            - "64:0b:11:27:fa:cc:91:17:e8:09:5e:3d:a9:a8:5b:10"
      - checkout
      - setup_remote_docker
      - docker/check
      - docker/build:
          image: $DOCKER_LOGIN/$CIRCLE_PROJECT_REPONAME
          tag: latest
      - docker/push:
          digest-path: /tmp/digest.txt
          image: $DOCKER_LOGIN/$CIRCLE_PROJECT_REPONAME
          tag: latest
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"
