version: 2.1

orbs:
  docker: circleci/docker@2.1.3

workflows:
  build:
    jobs:
      - build-and-push:
          context:
            - docker-hub-creds
          filters:
            branches:
              only: master

jobs:
  build-and-push:
    docker:
      - image: cimg/base:current
        auth:
          username: $DOCKER_LOGIN
          password: $DOCKER_PASSWORD
    steps:
      - add_ssh_keys:
          fingerprints:
            - "32:1e:50:ac:53:31:84:21:f6:07:49:51:91:f2:32:10"
      - checkout
      - setup_remote_docker
      - docker/check
      - docker/build:
          image: $DOCKER_LOGIN/$CIRCLE_PROJECT_REPONAME
      - docker/push:
          digest-path: /tmp/digest.txt
          image: $DOCKER_LOGIN/$CIRCLE_PROJECT_REPONAME
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"
